remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-redirect-from
logo: /assets/img/logo.png
title: Collin M Barrett
tagline: Senior Software Engineer | Memphis, TN
description: Collin Barrett is a senior software engineer in Memphis, TN specializing in tech like .NET, Azure, Entity Framework, Angular, and React.
twitter:
  username: collinbarrett
  card: summary
social:
  name: Collin Barrett
  links:
    - https://www.linkedin.com/in/collinbarrett
    - https://github.com/collinbarrett
    - https://stackoverflow.com/users/2343739/collin-barrett
    - https://www.goodreads.com/collinbarrett
    - https://twitter.com/collinbarrett
    - https://www.facebook.com/collinmbarrett
    - https://www.instagram.com/collinmbarrett
# webmaster_verifications:
#   google: 
#   bing: 
#   alexa: 
#   yandex: 
#   baidu: 
#   facebook: 

# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md