# remote_theme: pages-themes/minimal@v0.2.0
plugins:
# - jekyll-remote-theme
- jekyll-redirect-from
- jekyll-feed
- jekyll-sitemap
sass:
  sass_dir: assets/css/_sass
logo: /assets/img/logo_collinmbarrett.png
title: Collin M. Barrett
tagline: Senior Software Engineer | Memphis, TN
description: Collin Barrett is a senior software engineer in Memphis, TN specializing in tech like .NET, Azure, Entity Framework, Angular, and React.
author:
  twitter: collinbarrett
feed:
  posts_limit: 9999
  categories:
  - Code
  - InfoSec
  tags: true
twitter:
  username: collinbarrett
  card: summary
social:
  name: Collin Barrett
  links:
    - https://www.linkedin.com/in/collinbarrett
    - https://github.com/collinbarrett
    - https://stackoverflow.com/users/2343739/collin-barrett
    - https://www.goodreads.com/collinbarrett
    - https://twitter.com/collinbarrett
    - https://www.facebook.com/collinmbarrett
    - https://www.instagram.com/collinmbarrett